### ISSUE TITLE
Concerns about commit ' bases for the rest of the robot'

### ISSUE THREAD

**Issue by RustyBamboo** [ufieeehw/IEEE2018#1]
Seems that commit 37961bd84009da84d68921cff007dfc8e498b9f1 introduced object files and code that does not pertain to the actual source code. These probably should be generated outside of the repo and not tracked by git.

**Comment by OrangeHoopla** [comment]
Thanks for seeing that, sorry for the delayed response. And I look to more advise in the future! For now I'm just going to remove it but in the future I'll just place the packages themselves into the repository.
